name: relese

on:
  push:
    branches: [main, master]

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Build Next.js application
        run: npm run build

      - name: Pull Vercel Environment
        run: npm run vercel:var

      - name: Build Project Artifacts (Vercel)
        run: npm run vercel:build

      - name: Deploy to Vercel
        run: npm run vercel:deploy
